{{- if or .Values.azureWorkloadIdentity.clientId .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
  {{- if .Values.azureWorkloadIdentity.clientId }}
    azure.workload.identity/use: "true"
  {{- end }}
  annotations:
  {{- if and .Values.oras.authProviders.alibabacloudAcrBasicEnable .Values.oras.authProviders.alibabacloudAcrBasicEnabled.ramRoleName }}
    pod-identity.alibabacloud.com/role-name: {{ .Values.oras.authProviders.alibabacloudAcrBasicEnabled.ramRoleName }}
  {{- end }}
  name: {{ include "ratify.serviceAccountName" . }}
{{- end }}